import { Badge } from "@workspace/ui/components/badge";
import {
  Card,
  CardAction,
  CardDescription,
  CardFooter,
  CardHeader,
  CardTitle,
} from "@workspace/ui/components/card";
import { Clock3Icon, DownloadIcon, SparklesIcon } from "lucide-react";

export const analyticCards = [
  {
    title: "Demos Generated",
    value: 128,
    badge: {
      icon: SparklesIcon,
      label: "+18 this week",
    },
    description: "Successfully turned product URLs into interactive demos",
  },
  {
    title: "Demos Exported",
    value: 80,
    badge: {
      icon: DownloadIcon,
      label: "+12 today",
    },
    description: "Exported and shared across presentations, embeds, and links",
  },
  {
    title: "Remaining Demos",
    value: 20,
    badge: {
      label: "Pro Plan",
    },
    description: "Demo credits remaining before your plan resets",
  },
  {
    title: "Pending Generations",
    value: 6,
    badge: {
      icon: Clock3Icon,
      label: "Processing",
    },
    description: "Demos currently being generated by AI",
  },
];

export function AnalyticCards() {
  return (
    <div className="grid @5xl/main:grid-cols-4 @xl/main:grid-cols-2 grid-cols-1 gap-4">
      {analyticCards.map((card) => {
        const Icon = card.badge.icon;

        return (
          <Card className="@container/card shadow-none" key={card.title}>
            <CardHeader>
              <CardDescription>{card.title}</CardDescription>

              <CardTitle className="font-semibold @[250px]/card:text-3xl text-2xl tabular-nums">
                {card.value}
              </CardTitle>

              <CardAction>
                <Badge variant="outline">
                  {Icon ? <Icon className="size-3.5" /> : null}
                  {card.badge.label}
                </Badge>
              </CardAction>
            </CardHeader>

            <CardFooter className="border-0 bg-transparent">
              <p className="line-clamp-1 flex gap-2 font-medium text-sm">
                {card.description}
              </p>
            </CardFooter>
          </Card>
        );
      })}
    </div>
  );
}
