import {
  Card,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@castfy/ui/components/card";
import { Clock3Icon, DownloadIcon, SparklesIcon } from "lucide-react";

export const analyticCards = [
  {
    title: "Demos Generated",
    value: 128,
    badge: {
      icon: SparklesIcon,
      variant: "success",
      label: "+18 this week",
    },
    description: "Successfully turned product URLs into interactive demos",
  },
  {
    title: "Demos Exported",
    value: 80,
    badge: {
      icon: DownloadIcon,
      variant: "info",
      label: "+12 today",
    },
    description: "Exported and shared across presentations, embeds, and links",
  },
  {
    title: "Remaining Demos",
    value: 20,
    badge: {
      label: "Pro Plan",
      variant: "default",
    },
    description: "Demo credits remaining before your plan resets",
  },
  {
    title: "Pending Generations",
    value: 6,
    badge: {
      icon: Clock3Icon,
      variant: "warning",
      label: "Processing",
    },
    description: "Demos currently being generated by AI",
  },
];

export function AnalyticCards() {
  return (
    <div className="grid @5xl/main:grid-cols-4 @xl/main:grid-cols-2 grid-cols-1 gap-4 *:data-[slot=card]:bg-muted/50 *:data-[slot=card]:ring-0">
      {analyticCards.map((card) => (
        <Card className="@container/card shadow-none" key={card.title}>
          <CardHeader>
            <CardTitle className="font-semibold text-2xl tabular-nums">
              {card.value}
            </CardTitle>
            <CardDescription>{card.title}</CardDescription>
          </CardHeader>
        </Card>
      ))}
    </div>
  );
}
